# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.app_log import base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='',
  serialized_pb=_b('\n\rmonitor.proto\x1a\nbase.proto\"\xbf\x02\n\x0bMonitorItem\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.MonitorItemType\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x03\x12\x10\n\x08lantency\x18\x04 \x01(\x03\x12\x12\n\ntrace_code\x18\x05 \x01(\t\x12\x17\n\x06\x61\x63\x63\x65ss\x18\x06 \x01(\x0e\x32\x07.Access\x12\x0b\n\x03uri\x18\x07 \x01(\t\x12\x11\n\tis_active\x18\x08 \x01(\x08\x12\x14\n\x0c\x65rror_domain\x18\t \x01(\t\x12\x1e\n\x06metric\x18\n \x03(\x0b\x32\x0e.MonitorMetric\x12\x12\n\nstart_time\x18\x0b \x01(\x03\x12\x11\n\ttimestamp\x18\x0c \x01(\x03\x12\x0e\n\x06log_id\x18\r \x01(\t\x12%\n\nweb_metric\x18\x0e \x01(\x0b\x32\x11.MonitorWebMetric\"\xa3\x01\n\x10MonitorWebMetric\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0b\x66\x65tch_start\x18\x02 \x01(\x01\x12\x12\n\nshow_start\x18\x03 \x01(\x01\x12\x16\n\x0e\x66\x65tch_duration\x18\x04 \x01(\x01\x12\x1b\n\x13unfinished_progress\x18\x05 \x01(\x01\x12$\n\x1cunfinished_progress_duration\x18\x06 \x01(\x01\"\xc1\x02\n\rMonitorMetric\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x03\x12\x13\n\x0b\x66\x65tch_start\x18\x03 \x01(\x01\x12\x1c\n\x14\x64omain_look_up_start\x18\x04 \x01(\x01\x12\x1a\n\x12\x64omain_look_up_end\x18\x05 \x01(\x01\x12\x15\n\rconnect_start\x18\x06 \x01(\x01\x12\x1f\n\x17secure_connection_start\x18\x07 \x01(\x01\x12\x1d\n\x15secure_connection_end\x18\x08 \x01(\x01\x12\x13\n\x0b\x63onnect_end\x18\t \x01(\x01\x12\x15\n\rrequest_start\x18\n \x01(\x01\x12\x13\n\x0brequest_end\x18\x0b \x01(\x01\x12\x16\n\x0eresponse_start\x18\x0c \x01(\x01\x12\x14\n\x0cresponse_end\x18\r \x01(\x01\"B\n\x0bNewsMonitor\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x1a\n\x04item\x18\x02 \x03(\x0b\x32\x0c.MonitorItem*E\n\x0fMonitorItemType\x12\x0f\n\x0b\x45VENT_ERROR\x10\x00\x12\x10\n\x0c\x45VENT_SAMPLE\x10\x01\x12\x0f\n\x0b\x45VENT_DEBUG\x10\x02')
  ,
  dependencies=[base_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MONITORITEMTYPE = _descriptor.EnumDescriptor(
  name='MonitorItemType',
  full_name='MonitorItemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVENT_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_SAMPLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT_DEBUG', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=909,
  serialized_end=978,
)
_sym_db.RegisterEnumDescriptor(_MONITORITEMTYPE)

MonitorItemType = enum_type_wrapper.EnumTypeWrapper(_MONITORITEMTYPE)
EVENT_ERROR = 0
EVENT_SAMPLE = 1
EVENT_DEBUG = 2



_MONITORITEM = _descriptor.Descriptor(
  name='MonitorItem',
  full_name='MonitorItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MonitorItem.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='MonitorItem.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='MonitorItem.status', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lantency', full_name='MonitorItem.lantency', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trace_code', full_name='MonitorItem.trace_code', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='access', full_name='MonitorItem.access', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uri', full_name='MonitorItem.uri', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='MonitorItem.is_active', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_domain', full_name='MonitorItem.error_domain', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric', full_name='MonitorItem.metric', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='MonitorItem.start_time', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MonitorItem.timestamp', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_id', full_name='MonitorItem.log_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='web_metric', full_name='MonitorItem.web_metric', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=349,
)


_MONITORWEBMETRIC = _descriptor.Descriptor(
  name='MonitorWebMetric',
  full_name='MonitorWebMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='MonitorWebMetric.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetch_start', full_name='MonitorWebMetric.fetch_start', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='show_start', full_name='MonitorWebMetric.show_start', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetch_duration', full_name='MonitorWebMetric.fetch_duration', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unfinished_progress', full_name='MonitorWebMetric.unfinished_progress', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unfinished_progress_duration', full_name='MonitorWebMetric.unfinished_progress_duration', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=515,
)


_MONITORMETRIC = _descriptor.Descriptor(
  name='MonitorMetric',
  full_name='MonitorMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='MonitorMetric.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='MonitorMetric.status', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetch_start', full_name='MonitorMetric.fetch_start', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain_look_up_start', full_name='MonitorMetric.domain_look_up_start', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain_look_up_end', full_name='MonitorMetric.domain_look_up_end', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connect_start', full_name='MonitorMetric.connect_start', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secure_connection_start', full_name='MonitorMetric.secure_connection_start', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secure_connection_end', full_name='MonitorMetric.secure_connection_end', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connect_end', full_name='MonitorMetric.connect_end', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_start', full_name='MonitorMetric.request_start', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_end', full_name='MonitorMetric.request_end', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_start', full_name='MonitorMetric.response_start', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_end', full_name='MonitorMetric.response_end', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=839,
)


_NEWSMONITOR = _descriptor.Descriptor(
  name='NewsMonitor',
  full_name='NewsMonitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='NewsMonitor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='NewsMonitor.item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=907,
)

_MONITORITEM.fields_by_name['type'].enum_type = _MONITORITEMTYPE
_MONITORITEM.fields_by_name['access'].enum_type = base_pb2._ACCESS
_MONITORITEM.fields_by_name['metric'].message_type = _MONITORMETRIC
_MONITORITEM.fields_by_name['web_metric'].message_type = _MONITORWEBMETRIC
_NEWSMONITOR.fields_by_name['header'].message_type = base_pb2._HEADER
_NEWSMONITOR.fields_by_name['item'].message_type = _MONITORITEM
DESCRIPTOR.message_types_by_name['MonitorItem'] = _MONITORITEM
DESCRIPTOR.message_types_by_name['MonitorWebMetric'] = _MONITORWEBMETRIC
DESCRIPTOR.message_types_by_name['MonitorMetric'] = _MONITORMETRIC
DESCRIPTOR.message_types_by_name['NewsMonitor'] = _NEWSMONITOR
DESCRIPTOR.enum_types_by_name['MonitorItemType'] = _MONITORITEMTYPE

MonitorItem = _reflection.GeneratedProtocolMessageType('MonitorItem', (_message.Message,), dict(
  DESCRIPTOR = _MONITORITEM,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MonitorItem)
  ))
_sym_db.RegisterMessage(MonitorItem)

MonitorWebMetric = _reflection.GeneratedProtocolMessageType('MonitorWebMetric', (_message.Message,), dict(
  DESCRIPTOR = _MONITORWEBMETRIC,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MonitorWebMetric)
  ))
_sym_db.RegisterMessage(MonitorWebMetric)

MonitorMetric = _reflection.GeneratedProtocolMessageType('MonitorMetric', (_message.Message,), dict(
  DESCRIPTOR = _MONITORMETRIC,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:MonitorMetric)
  ))
_sym_db.RegisterMessage(MonitorMetric)

NewsMonitor = _reflection.GeneratedProtocolMessageType('NewsMonitor', (_message.Message,), dict(
  DESCRIPTOR = _NEWSMONITOR,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:NewsMonitor)
  ))
_sym_db.RegisterMessage(NewsMonitor)


# @@protoc_insertion_point(module_scope)
